apiVersion: v1
kind: Service
metadata:
  name: packcheck-api-svc
  namespace: default
  labels:
    app: packcheck-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: packcheck-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: packcheck-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
spec:
  rules:
    - host: api.packcheck.gov.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: packcheck-api-svc
                port:
                  number: 80
